const ALL_BANIS_DATA = [
  {
    ID: 2,
    token: "japji",
    gurmukhi: "jpujI swihb",
    gurmukhiUni: "ਜਪੁਜੀ ਸਾਹਿਬ",
    transliteration: "japujee saahib",
    transliterations: {
      english: "japujee saahib",
      hindi: "जपुजी साहिब",
      en: "japujee saahib",
      hi: "जपुजी साहिब",
      ipa: "d͡ʒəpʊd͡ʒi sɑhɪb",
      ur: "جپجیِ ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 3,
    token: "shabadhazare",
    gurmukhi: "Sbd hzwry",
    gurmukhiUni: "ਸ਼ਬਦ ਹਜ਼ਾਰੇ",
    transliteration: "shabadh hazaare",
    transliterations: {
      english: "shabadh hazaare",
      hindi: "शबद हज़ारे",
      en: "shabadh hazaare",
      hi: "शबद हज़ारे",
      ipa: "ʃəbəd̪ həzɑre",
      ur: "شبد هزارے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 4,
    token: "jaap",
    gurmukhi: "jwpu swihb",
    gurmukhiUni: "ਜਾਪੁ ਸਾਹਿਬ",
    transliteration: "jaap saahib",
    transliterations: {
      english: "jaap saahib",
      hindi: "जापु साहिब",
      en: "jaap saahib",
      hi: "जापु साहिब",
      ipa: "d͡ʒɑp sɑhɪb",
      ur: "جاپ ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 5,
    token: "shabadhazare10",
    gurmukhi: "Sbd hzwry pwiqSwhI 10",
    gurmukhiUni: "ਸ਼ਬਦ ਹਜ਼ਾਰੇ ਪਾਤਿਸ਼ਾਹੀ ੧੦",
    transliteration: "shabadh hazaare paatishaahee 10",
    transliterations: {
      english: "shabadh hazaare paatishaahee 10",
      hindi: "शबद हज़ारे पातिशाही १०",
      en: "shabadh hazaare paatishaahee 10",
      hi: "शबद हज़ारे पातिशाही १०",
      ipa: "ʃəbəd̪ həzɑre pɑt̪ɪʃɑhi 1ə0",
      ur: "شبد هزارے پاتشاهیِ ۱۰",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 6,
    token: "svaiye",
    gurmukhi: "qÍ pRswid sv`Xy (sRwvg su`D)",
    gurmukhiUni: "ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸਵੱਯੇ (ਸ੍ਰਾਵਗ ਸੁੱਧ)",
    transliteration: "tavai prasaadh sava'ye (sraavag su'dh)",
    transliterations: {
      english: "tavai prasaadh sava'ye (sraavag su'dh)",
      hindi: "त्व प्रसादि सवय्ये (स्रावग सुद्ध)",
      en: "tavai prasaadh sava'ye (sraavag su'dh)",
      hi: "त्व प्रसादि सवय्ये (स्रावग सुद्ध)",
      ipa: "t̪ʋ pɹəsɑd̪ səʋje (sɹɑʋəG sʊt̪ə̀)",
      ur: "تو پرساد سوّےے (سراوگ سُّدھ)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 7,
    token: "svaiyedeenan",
    gurmukhi: "qÍ pRswid sv`Xy (dInn kI)",
    gurmukhiUni: "ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸਵੱਯੇ (ਦੀਨਨ ਕੀ)",
    transliteration: "tavai prasaadh sava'ye (dheenan kee)",
    transliterations: {
      english: "tavai prasaadh sava'ye (dheenan kee)",
      hindi: "त्व प्रसादि सवय्ये (दीनन की)",
      en: "tavai prasaadh sava'ye (dheenan kee)",
      hi: "त्व प्रसादि सवय्ये (दीनन की)",
      ipa: "t̪ʋ pɹəsɑd̪ səʋje (d̪inən ki)",
      ur: "تو پرساد سوّےے (دیٍنن کیِ)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 8,
    token: "akaalustatchaupai",
    gurmukhi: "Akwl ausqq cOpeI",
    gurmukhiUni: "ਅਕਾਲ ਉਸਤਤ ਚੌਪਈ",
    transliteration: "akaal usatat chauapiee",
    transliterations: {
      english: "akaal usatat chauapiee",
      hindi: "अकाल उसतत चौपई",
      en: "akaal usatat chauapiee",
      hi: "अकाल उसतत चौपई",
      ipa: "əkɑl oʊsət̪ət̪ t͡ʃɒəpei",
      ur: "اکال اُستت چَوپای",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 9,
    token: "chaupai",
    gurmukhi: "bynqI cOpeI swihb",
    gurmukhiUni: "ਬੇਨਤੀ ਚੌਪਈ ਸਾਹਿਬ",
    transliteration: "benatee chauapiee saahib",
    transliterations: {
      english: "benatee chauapiee saahib",
      hindi: "बेनती चौपई साहिब",
      en: "benatee chauapiee saahib",
      hi: "बेनती चौपई साहिब",
      ipa: "benət̪i t͡ʃɒəpei sɑhɪb",
      ur: "بےنتیِ چَوپای ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 10,
    token: "anand",
    gurmukhi: "Anµdu swihb",
    gurmukhiUni: "ਅਨੰਦੁ ਸਾਹਿਬ",
    transliteration: "ana(n)dh saahib",
    transliterations: {
      english: "ana(n)dh saahib",
      hindi: "अनंदु साहिब",
      en: "ana(n)dh saahib",
      hi: "अनंदु साहिब",
      ipa: "ənəⁿd̪ sɑhɪb",
      ur: "انµد ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 11,
    token: "lavaa",
    gurmukhi: "lwvW",
    gurmukhiUni: "ਲਾਵਾਂ",
    transliteration: "laavaa(n)",
    transliterations: {
      english: "laavaa(n)",
      hindi: "लावाँ",
      en: "laavaa(n)",
      hi: "लावाँ",
      ipa: "lɑʋɑⁿ",
      ur: "لاواں",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 12,
    token: "athchandichariter",
    gurmukhi: "AQ cMfIcirqR",
    gurmukhiUni: "ਅਥ ਚੰਡੀਚਰਿਤ੍ਰ",
    transliteration: "ath cha(n)ddeecharitr",
    transliterations: {
      english: "ath cha(n)ddeecharitr",
      hindi: "अथ चंडीचरित्र",
      en: "ath cha(n)ddeecharitr",
      hi: "अथ चंडीचरित्र",
      ipa: "ət̪ʰ t͡ʃəŋɖit͡ʃərɪt̪ɹ",
      ur: "اتھ چںڈیِچرتر",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 13,
    token: "chandidivar",
    gurmukhi: "cMfI dI vwr",
    gurmukhiUni: "ਚੰਡੀ ਦੀ ਵਾਰ",
    transliteration: "cha(n)ddee dhee vaar",
    transliterations: {
      english: "cha(n)ddee dhee vaar",
      hindi: "चंडी दी वार",
      en: "cha(n)ddee dhee vaar",
      hi: "चंडी दी वार",
      ipa: "t͡ʃəŋɖi d̪i ʋɑr",
      ur: "چںڈیِ دیِ وار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 14,
    token: "kuchji",
    gurmukhi: "kucjI",
    gurmukhiUni: "ਕੁਚਜੀ",
    transliteration: "kuchajee",
    transliterations: {
      english: "kuchajee",
      hindi: "कुचजी",
      en: "kuchajee",
      hi: "कुचजी",
      ipa: "kʊt͡ʃəd͡ʒi",
      ur: "کُچجیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 15,
    token: "suchji",
    gurmukhi: "sucjI",
    gurmukhiUni: "ਸੁਚਜੀ",
    transliteration: "suchajee",
    transliterations: {
      english: "suchajee",
      hindi: "सुचजी",
      en: "suchajee",
      hi: "सुचजी",
      ipa: "sʊt͡ʃəd͡ʒi",
      ur: "سُچجیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 16,
    token: "gunvanti",
    gurmukhi: "guxvMqI",
    gurmukhiUni: "ਗੁਣਵੰਤੀ",
    transliteration: "gunava(n)tee",
    transliterations: {
      english: "gunava(n)tee",
      hindi: "गुणवंती",
      en: "gunava(n)tee",
      hi: "गुणवंती",
      ipa: "Gʊɳəʋəŋt̪i",
      ur: "گُݨوںتیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 17,
    token: "funhem5",
    gurmukhi: "Punhy mhlw 5",
    gurmukhiUni: "ਫੁਨਹੇ ਮਹਲਾ ੫",
    transliteration: "funahe mahalaa panjavaa",
    transliterations: {
      english: "funahe mahalaa panjavaa",
      hindi: "फुनहे महला ५",
      en: "funahe mahalaa panjavaa",
      hi: "फुनहे महला ५",
      ipa: "fʊnəhe məhəlɑ pəŋd͡ʒʋɑ",
      ur: "پھُنهے مهلا ۵",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 18,
    token: "chaubole",
    gurmukhi: "cauboly",
    gurmukhiUni: "ਚਉਬੋਲੇ",
    transliteration: "chaubole",
    transliterations: {
      english: "chaubole",
      hindi: "चउबोले",
      en: "chaubole",
      hi: "चउबोले",
      ipa: "t͡ʃoʊbɔle",
      ur: "چابولے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 19,
    token: "shastarnaammala",
    gurmukhi: "SsqR nwm mwlw",
    gurmukhiUni: "ਸ਼ਸਤ੍ਰ ਨਾਮ ਮਾਲਾ",
    transliteration: "shasatr naam maalaa",
    transliterations: {
      english: "shasatr naam maalaa",
      hindi: "शसत्र नाम माला",
      en: "shasatr naam maalaa",
      hi: "शसत्र नाम माला",
      ipa: "ʃəsət̪ɹ nɑm mɑlɑ",
      ur: "شستر نام مالا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 21,
    token: "rehras",
    gurmukhi: "rhrwis swihb",
    gurmukhiUni: "ਰਹਰਾਸਿ ਸਾਹਿਬ",
    transliteration: "raharaas saahib",
    transliterations: {
      english: "raharaas saahib",
      hindi: "रहरासि साहिब",
      en: "raharaas saahib",
      hi: "रहरासि साहिब",
      ipa: "rəhərɑs sɑhɪb",
      ur: "رهراس ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 22,
    token: "aarti",
    gurmukhi: "AwrqI",
    gurmukhiUni: "ਆਰਤੀ",
    transliteration: "aaratee",
    transliterations: {
      english: "aaratee",
      hindi: "आरती",
      en: "aaratee",
      hi: "आरती",
      ipa: "əɑrət̪i",
      ur: "آرتیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 23,
    token: "sohila",
    gurmukhi: "soihlw swihb",
    gurmukhiUni: "ਸੋਹਿਲਾ ਸਾਹਿਬ",
    transliteration: "sohilaa saahib",
    transliterations: {
      english: "sohilaa saahib",
      hindi: "सोहिला साहिब",
      en: "sohilaa saahib",
      hi: "सोहिला साहिब",
      ipa: "sɔhɪlɑ sɑhɪb",
      ur: "سوهلا ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 24,
    token: "ardas",
    gurmukhi: "Ardws",
    gurmukhiUni: "ਅਰਦਾਸ",
    transliteration: "aradhaas",
    transliterations: {
      english: "aradhaas",
      hindi: "अरदास",
      en: "aradhaas",
      hi: "अरदास",
      ipa: "ərəd̪ɑs",
      ur: "ارداس",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 25,
    token: "bhagautiastotr",
    gurmukhi: "sRI BgauqI AsqoqR (pMQ pRkwS)",
    gurmukhiUni: "ਸ੍ਰੀ ਭਗਉਤੀ ਅਸਤੋਤ੍ਰ (ਪੰਥ ਪ੍ਰਕਾਸ਼)",
    transliteration: "sree bhagautee asatotr (pa(n)th prakaash)",
    transliterations: {
      english: "sree bhagautee asatotr (pa(n)th prakaash)",
      hindi: "स्री भगउती असतोत्र (पंथ प्रकाश)",
      en: "sree bhagautee asatotr (pa(n)th prakaash)",
      hi: "स्री भगउती असतोत्र (पंथ प्रकाश)",
      ipa: "sɹi ɓəGoʊt̪i əsət̪ɔt̪ɹ (pəŋt̪ʰ pɹəkɑʃ)",
      ur: "سریِ بھگاتیِ استوتر (پںتھ پرکاش)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 26,
    token: "bhagautiastotrhazoor",
    gurmukhi: "sRI BgauqI AsqoqR (sRI hzUr swihb)",
    gurmukhiUni: "ਸ੍ਰੀ ਭਗਉਤੀ ਅਸਤੋਤ੍ਰ (ਸ੍ਰੀ ਹਜ਼ੂਰ ਸਾਹਿਬ)",
    transliteration: "sree bhagautee asatotr (sree hazoor saahib)",
    transliterations: {
      english: "sree bhagautee asatotr (sree hazoor saahib)",
      hindi: "स्री भगउती असतोत्र (स्री हज़ूर साहिब)",
      en: "sree bhagautee asatotr (sree hazoor saahib)",
      hi: "स्री भगउती असतोत्र (स्री हज़ूर साहिब)",
      ipa: "sɹi ɓəGoʊt̪i əsət̪ɔt̪ɹ (sɹi həzur sɑhɪb)",
      ur: "سریِ بھگاتیِ استوتر (سریِ هزُور ساهب)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 27,
    token: "baarehmaha",
    gurmukhi: "bwrh mwhw mWJ",
    gurmukhiUni: "ਬਾਰਹ ਮਾਹਾ ਮਾਂਝ",
    transliteration: "baareh maahaa maa(n)jh",
    transliterations: {
      english: "baareh maahaa maa(n)jh",
      hindi: "बारह माहा माँझ",
      en: "baareh maahaa maa(n)jh",
      hi: "बारह माहा माँझ",
      ipa: "bɑrəh mɑhɑ mɑⁿəɖ͡ʐ",
      ur: "باره ماها ماںجھ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 28,
    token: "baarehmahasvaye",
    gurmukhi: "bwrh mwhw svYXw",
    gurmukhiUni: "ਬਾਰਹ ਮਾਹਾ ਸਵੈਯਾ",
    transliteration: "baareh maahaa savaiyaa",
    transliterations: {
      english: "baareh maahaa savaiyaa",
      hindi: "बारह माहा सवैया",
      en: "baareh maahaa savaiyaa",
      hi: "बारह माहा सवैया",
      ipa: "bɑrəh mɑhɑ səʋæjɑ",
      ur: "باره ماها سوَےےا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 29,
    token: "akalustat",
    gurmukhi: "Akwl ausqq",
    gurmukhiUni: "ਅਕਾਲ ਉਸਤਤ",
    transliteration: "akaal usatat",
    transliterations: {
      english: "akaal usatat",
      hindi: "अकाल उसतत",
      en: "akaal usatat",
      hi: "अकाल उसतत",
      ipa: "əkɑl oʊsət̪ət̪",
      ur: "اکال اُستت",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 30,
    token: "salokm9",
    gurmukhi: "slok mhlw 9",
    gurmukhiUni: "ਸਲੋਕ ਮਹਲਾ ੯",
    transliteration: "salok mahalaa nauvaa",
    transliterations: {
      english: "salok mahalaa nauvaa",
      hindi: "सलोक महला ९",
      en: "salok mahalaa nauvaa",
      hi: "सलोक महला ९",
      ipa: "səlɔk məhəlɑ nɑʋɑ",
      ur: "سلوک مهلا ۹",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 31,
    token: "sukhmani",
    gurmukhi: "suKmnI swihb",
    gurmukhiUni: "ਸੁਖਮਨੀ ਸਾਹਿਬ",
    transliteration: "sukhamanee saahib",
    transliterations: {
      english: "sukhamanee saahib",
      hindi: "सुखमनी साहिब",
      en: "sukhamanee saahib",
      hi: "सुखमनी साहिब",
      ipa: "sʊkʰəməni sɑhɪb",
      ur: "سُکھمنیِ ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 32,
    token: "sukhmana",
    gurmukhi: "suKmnw swihb",
    gurmukhiUni: "ਸੁਖਮਨਾ ਸਾਹਿਬ",
    transliteration: "sukhamanaa saahib",
    transliterations: {
      english: "sukhamanaa saahib",
      hindi: "सुखमना साहिब",
      en: "sukhamanaa saahib",
      hi: "सुखमना साहिब",
      ipa: "sʊkʰəmənɑ sɑhɪb",
      ur: "سُکھمنا ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 33,
    token: "bavanakhree",
    gurmukhi: "bwvn AKrI",
    gurmukhiUni: "ਬਾਵਨ ਅਖਰੀ",
    transliteration: "baavan akharee",
    transliterations: {
      english: "baavan akharee",
      hindi: "बावन अखरी",
      en: "baavan akharee",
      hi: "बावन अखरी",
      ipa: "bɑʋən əkʰəri",
      ur: "باون اکھریِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 34,
    token: "sidhgosht",
    gurmukhi: "isD gosit",
    gurmukhiUni: "ਸਿਧ ਗੋਸਟਿ",
    transliteration: "sidh gosaT",
    transliterations: {
      english: "sidh gosaT",
      hindi: "सिध गोसटि",
      en: "sidh gosaT",
      hi: "सिध गोसटि",
      ipa: "sɪt̪ə̀ Gɔsəʈ",
      ur: "سِدھ گوسٹ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 35,
    token: "dhakhnioankar",
    gurmukhi: "dKxI EAMkwru",
    gurmukhiUni: "ਦਖਣੀ ਓਅੰਕਾਰੁ",
    transliteration: "dhakhanee oa(n)kaaru",
    transliterations: {
      english: "dhakhanee oa(n)kaaru",
      hindi: "दखणी ओअंकारु",
      en: "dhakhanee oa(n)kaaru",
      hi: "दखणी ओअंकारु",
      ipa: "d̪əkʰəɳi oəŋkɑrʊ",
      ur: "دکھݨیِ اواںکار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 36,
    token: "dukhbhanjani",
    gurmukhi: "duK BMjnI swihb",
    gurmukhiUni: "ਦੁਖ ਭੰਜਨੀ ਸਾਹਿਬ",
    transliteration: "dhukh bha(n)janee saahib",
    transliterations: {
      english: "dhukh bha(n)janee saahib",
      hindi: "दुख भंजनी साहिब",
      en: "dhukh bha(n)janee saahib",
      hi: "दुख भंजनी साहिब",
      ipa: "d̪ʊkʰ ɓəŋd͡ʒəni sɑhɪb",
      ur: "دُکھ بھںجنیِ ساهب",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 38,
    token: "raagmala",
    gurmukhi: "rwg mwlw",
    gurmukhiUni: "ਰਾਗ ਮਾਲਾ",
    transliteration: "raag maalaa",
    transliterations: {
      english: "raag maalaa",
      hindi: "राग माला",
      en: "raag maalaa",
      hi: "राग माला",
      ipa: "rɑG mɑlɑ",
      ur: "راگ مالا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 39,
    token: "baavanakhrikabirjee",
    gurmukhi: "bwvn AKrI kbIr jIau kI",
    gurmukhiUni: "ਬਾਵਨ ਅਖਰੀ ਕਬੀਰ ਜੀਉ ਕੀ",
    transliteration: "baavan akharee kabeer jeeau kee",
    transliterations: {
      english: "baavan akharee kabeer jeeau kee",
      hindi: "बावन अखरी कबीर जीउ की",
      en: "baavan akharee kabeer jeeau kee",
      hi: "बावन अखरी कबीर जीउ की",
      ipa: "bɑʋən əkʰəri kəbir d͡ʒio ki",
      ur: "باون اکھریِ کبیِر جیِا کیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 40,
    token: "ghorrian",
    gurmukhi: "GoVIAw",
    gurmukhiUni: "ਘੋੜੀਆ",
    transliteration: "ghoReeaa",
    transliterations: {
      english: "ghoReeaa",
      hindi: "घोड़ीआ",
      en: "ghoReeaa",
      hi: "घोड़ीआ",
      ipa: "Gʰɔɽiəɑ",
      ur: "گھوڑیِآ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 41,
    token: "karhalai",
    gurmukhi: "krhly",
    gurmukhiUni: "ਕਰਹਲੇ",
    transliteration: "karahale",
    transliterations: {
      english: "karahale",
      hindi: "करहले",
      en: "karahale",
      hi: "करहले",
      ipa: "kərəhəle",
      ur: "کرهلے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 42,
    token: "birharre",
    gurmukhi: "ibrhVy",
    gurmukhiUni: "ਬਿਰਹੜੇ",
    transliteration: "birahaRe",
    transliterations: {
      english: "birahaRe",
      hindi: "बिरहड़े",
      en: "birahaRe",
      hi: "बिरहड़े",
      ipa: "bɪrəhəɽe",
      ur: "بِرهڑے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 43,
    token: "patteelikhee",
    gurmukhi: "ptI ilKI",
    gurmukhiUni: "ਪਟੀ ਲਿਖੀ",
    transliteration: "paTee likhee",
    transliterations: {
      english: "paTee likhee",
      hindi: "पटी लिखी",
      en: "paTee likhee",
      hi: "पटी लिखी",
      ipa: "pəʈi lɪkʰi",
      ur: "پٹیِ لکھیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 44,
    token: "patteem3",
    gurmukhi: "ptI mhlw 3",
    gurmukhiUni: "ਪਟੀ ਮਹਲਾ ੩",
    transliteration: "paTee mahalaa teejaa",
    transliterations: {
      english: "paTee mahalaa teejaa",
      hindi: "पटी महला ३",
      en: "paTee mahalaa teejaa",
      hi: "पटी महला ३",
      ipa: "pəʈi məhəlɑ t̪id͡ʒɑ",
      ur: "پٹیِ مهلا ۳",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 45,
    token: "ruteem5",
    gurmukhi: "mhlw 5 ruqI",
    gurmukhiUni: "ਮਹਲਾ ੫ ਰੁਤੀ",
    transliteration: "mahalaa panjavaa rutee",
    transliterations: {
      english: "mahalaa panjavaa rutee",
      hindi: "महला ५ रुती",
      en: "mahalaa panjavaa rutee",
      hi: "महला ५ रुती",
      ipa: "məhəlɑ pəŋd͡ʒʋɑ rʊt̪i",
      ur: "مهلا ۵ رُتیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 46,
    token: "sadd",
    gurmukhi: "rwmklI sdu",
    gurmukhiUni: "ਰਾਮਕਲੀ ਸਦੁ",
    transliteration: "raamakalee sadhu",
    transliterations: {
      english: "raamakalee sadhu",
      hindi: "रामकली सदु",
      en: "raamakalee sadhu",
      hi: "रामकली सदु",
      ipa: "rɑməkəli səd̪ʊ",
      ur: "رامکلیِ سد",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 47,
    token: "thitteekabirjee",
    gurmukhi: "iQqMØI kbIr jI kMØI",
    gurmukhiUni: "ਥਿਤੰੀ ਕਬੀਰ ਜੀ ਕੰੀ",
    transliteration: "thita(n)ee kabeer jee ka(n)ee",
    transliterations: {
      english: "thita(n)ee kabeer jee ka(n)ee",
      hindi: "थितीं कबीर जी कीं",
      en: "thita(n)ee kabeer jee ka(n)ee",
      hi: "थितीं कबीर जी कीं",
      ipa: "t̪ʰɪt̪əŋi kəbir d͡ʒi kəŋi",
      ur: "تھِتںØیِ کبیِر جیِ کںØیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 48,
    token: "thitteem1",
    gurmukhi: "iQqI mhlw 1",
    gurmukhiUni: "ਥਿਤੀ ਮਹਲਾ ੧",
    transliteration: "thitee mahalaa pehilaa",
    transliterations: {
      english: "thitee mahalaa pehilaa",
      hindi: "थिती महला १",
      en: "thitee mahalaa pehilaa",
      hi: "थिती महला १",
      ipa: "t̪ʰɪt̪i məhəlɑ pəhɪlɑ",
      ur: "تھِتیِ مهلا ۱",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 49,
    token: "thitteem5",
    gurmukhi: "iQqI mhlw 5",
    gurmukhiUni: "ਥਿਤੀ ਮਹਲਾ ੫",
    transliteration: "thitee mahalaa panjavaa",
    transliterations: {
      english: "thitee mahalaa panjavaa",
      hindi: "थिती महला ५",
      en: "thitee mahalaa panjavaa",
      hi: "थिती महला ५",
      ipa: "t̪ʰɪt̪i məhəlɑ pəŋd͡ʒʋɑ",
      ur: "تھِتیِ مهلا ۵",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 50,
    token: "vaarkabirjee",
    gurmukhi: "gauVI vwr kbIr jIau ky",
    gurmukhiUni: "ਗਉੜੀ ਵਾਰ ਕਬੀਰ ਜੀਉ ਕੇ",
    transliteration: "gauRee vaar kabeer jeeau ke",
    transliterations: {
      english: "gauRee vaar kabeer jeeau ke",
      hindi: "गउड़ी वार कबीर जीउ के",
      en: "gauRee vaar kabeer jeeau ke",
      hi: "गउड़ी वार कबीर जीउ के",
      ipa: "Goʊɽi ʋɑr kəbir d͡ʒio ke",
      ur: "گاڑیِ وار کبیِر جیِا کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 51,
    token: "vaarsat",
    gurmukhi: "iblwvlu mhlw 3 vwr sq",
    gurmukhiUni: "ਬਿਲਾਵਲੁ ਮਹਲਾ ੩ ਵਾਰ ਸਤ",
    transliteration: "bilaaval mahalaa teejaa vaar sat",
    transliterations: {
      english: "bilaaval mahalaa teejaa vaar sat",
      hindi: "बिलावलु महला ३ वार सत",
      en: "bilaaval mahalaa teejaa vaar sat",
      hi: "बिलावलु महला ३ वार सत",
      ipa: "bɪlɑʋəl məhəlɑ t̪id͡ʒɑ ʋɑr sət̪",
      ur: "بِلاول مهلا ۳ وار ست",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 52,
    token: "vanjaara",
    gurmukhi: "vxjwrw",
    gurmukhiUni: "ਵਣਜਾਰਾ",
    transliteration: "vanajaaraa",
    transliterations: {
      english: "vanajaaraa",
      hindi: "वणजारा",
      en: "vanajaaraa",
      hi: "वणजारा",
      ipa: "ʋəɳəd͡ʒɑrɑ",
      ur: "وݨجارا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 53,
    token: "ogardanti",
    gurmukhi: "augRdMqI",
    gurmukhiUni: "ਉਗ੍ਰਦੰਤੀ",
    transliteration: "augradha(n)tee",
    transliterations: {
      english: "augradha(n)tee",
      hindi: "उग्रदंती",
      en: "augradha(n)tee",
      hi: "उग्रदंती",
      ipa: "oʊGɹəd̪əŋt̪i",
      ur: "اُگردںتیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 55,
    token: "sriraag",
    gurmukhi: "rwgu isrIrwgu (kbIr jIau kw)",
    gurmukhiUni: "ਰਾਗੁ ਸਿਰੀਰਾਗੁ (ਕਬੀਰ ਜੀਉ ਕਾ)",
    transliteration: "raag sireeraag (kabeer jeeau kaa)",
    transliterations: {
      english: "raag sireeraag (kabeer jeeau kaa)",
      hindi: "रागु सिरीरागु (कबीर जीउ का)",
      en: "raag sireeraag (kabeer jeeau kaa)",
      hi: "रागु सिरीरागु (कबीर जीउ का)",
      ipa: "rɑG sɪrirɑG (kəbir d͡ʒio kɑ)",
      ur: "راگ سریِراگ (کبیِر جیِا کا)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 56,
    token: "gauri",
    gurmukhi: "rwgu gauVI",
    gurmukhiUni: "ਰਾਗੁ ਗਉੜੀ",
    transliteration: "raag gauRee",
    transliterations: {
      english: "raag gauRee",
      hindi: "रागु गउड़ी",
      en: "raag gauRee",
      hi: "रागु गउड़ी",
      ipa: "rɑG Goʊɽi",
      ur: "راگ گاڑیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 57,
    token: "aasa",
    gurmukhi: "rwgu Awsw",
    gurmukhiUni: "ਰਾਗੁ ਆਸਾ",
    transliteration: "raag aasaa",
    transliterations: {
      english: "raag aasaa",
      hindi: "रागु आसा",
      en: "raag aasaa",
      hi: "रागु आसा",
      ipa: "rɑG əɑsɑ",
      ur: "راگ آسا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 58,
    token: "gujri",
    gurmukhi: "rwgu gUjrI",
    gurmukhiUni: "ਰਾਗੁ ਗੂਜਰੀ",
    transliteration: "raag goojaree",
    transliterations: {
      english: "raag goojaree",
      hindi: "रागु गूजरी",
      en: "raag goojaree",
      hi: "रागु गूजरी",
      ipa: "rɑG Gud͡ʒəri",
      ur: "راگ گُوجریِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 59,
    token: "sorat",
    gurmukhi: "rwgu soriT",
    gurmukhiUni: "ਰਾਗੁ ਸੋਰਠਿ",
    transliteration: "raag soraTh",
    transliterations: {
      english: "raag soraTh",
      hindi: "रागु सोरठि",
      en: "raag soraTh",
      hi: "रागु सोरठि",
      ipa: "rɑG sɔrəʈʰ",
      ur: "راگ سورٹھ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 60,
    token: "dhanasari",
    gurmukhi: "rwgu DnwsrI",
    gurmukhiUni: "ਰਾਗੁ ਧਨਾਸਰੀ",
    transliteration: "raag dhanaasaree",
    transliterations: {
      english: "raag dhanaasaree",
      hindi: "रागु धनासरी",
      en: "raag dhanaasaree",
      hi: "रागु धनासरी",
      ipa: "rɑG t̪ənɑsəri",
      ur: "راگ دھناسریِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 61,
    token: "jaitsree",
    gurmukhi: "rwgu jYqsrI",
    gurmukhiUni: "ਰਾਗੁ ਜੈਤਸਰੀ",
    transliteration: "raag jaitasaree",
    transliterations: {
      english: "raag jaitasaree",
      hindi: "रागु जैतसरी",
      en: "raag jaitasaree",
      hi: "रागु जैतसरी",
      ipa: "rɑG d͡ʒæt̪əsəri",
      ur: "راگ جَےتسریِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 62,
    token: "toddee",
    gurmukhi: "rwgu tofI (bwxI BgqW kI)",
    gurmukhiUni: "ਰਾਗੁ ਟੋਡੀ (ਬਾਣੀ ਭਗਤਾਂ ਕੀ)",
    transliteration: "raag Toddee (baanee bhagataa(n) kee)",
    transliterations: {
      english: "raag Toddee (baanee bhagataa(n) kee)",
      hindi: "रागु टोडी (बाणी भगताँ की)",
      en: "raag Toddee (baanee bhagataa(n) kee)",
      hi: "रागु टोडी (बाणी भगताँ की)",
      ipa: "rɑG ʈɔɖi (bɑɳi ɓəGət̪ɑⁿ ki)",
      ur: "راگ ٹوڈیِ (باݨیِ بھگتاں کیِ)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 63,
    token: "tilang",
    gurmukhi: "rwgu iqlMg (bwxI Bgqw kI kbIr jI)",
    gurmukhiUni: "ਰਾਗੁ ਤਿਲੰਗ (ਬਾਣੀ ਭਗਤਾ ਕੀ ਕਬੀਰ ਜੀ)",
    transliteration: "raag tila(n)g (baanee bhagataa kee kabeer jee)",
    transliterations: {
      english: "raag tila(n)g (baanee bhagataa kee kabeer jee)",
      hindi: "रागु तिलंग (बाणी भगता की कबीर जी)",
      en: "raag tila(n)g (baanee bhagataa kee kabeer jee)",
      hi: "रागु तिलंग (बाणी भगता की कबीर जी)",
      ipa: "rɑG t̪ɪləŋG (bɑɳi ɓəGət̪ɑ ki kəbir d͡ʒi)",
      ur: "راگ تلںگ (باݨیِ بھگتا کیِ کبیِر جیِ)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 64,
    token: "soohee",
    gurmukhi: "rwgu sUhI",
    gurmukhiUni: "ਰਾਗੁ ਸੂਹੀ",
    transliteration: "raag soohee",
    transliterations: {
      english: "raag soohee",
      hindi: "रागु सूही",
      en: "raag soohee",
      hi: "रागु सूही",
      ipa: "rɑG suhi",
      ur: "راگ سُوهیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 65,
    token: "bilaaval",
    gurmukhi: "rwgu iblwvlu",
    gurmukhiUni: "ਰਾਗੁ ਬਿਲਾਵਲੁ",
    transliteration: "raag bilaavalu",
    transliterations: {
      english: "raag bilaavalu",
      hindi: "रागु बिलावलु",
      en: "raag bilaavalu",
      hi: "रागु बिलावलु",
      ipa: "rɑG bɪlɑʋəlʊ",
      ur: "راگ بلاول",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 66,
    token: "gond",
    gurmukhi: "rwgu goNf",
    gurmukhiUni: "ਰਾਗੁ ਗੋਂਡ",
    transliteration: "raag go(n)dd",
    transliterations: {
      english: "raag go(n)dd",
      hindi: "रागु गोंड",
      en: "raag go(n)dd",
      hi: "रागु गोंड",
      ipa: "rɑG Gɔⁿɖ",
      ur: "راگ گوںڈ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 67,
    token: "ramkali",
    gurmukhi: "rwgu rwmklI (sdu)",
    gurmukhiUni: "ਰਾਗੁ ਰਾਮਕਲੀ (ਸਦੁ)",
    transliteration: "raag raamakalee (sadhu)",
    transliterations: {
      english: "raag raamakalee (sadhu)",
      hindi: "रागु रामकली (सदु)",
      en: "raag raamakalee (sadhu)",
      hi: "रागु रामकली (सदु)",
      ipa: "rɑG rɑməkəli (səd̪ʊ)",
      ur: "راگ رامکلیِ (سد)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 68,
    token: "maaligauri",
    gurmukhi: "rwgu mwlI gauVw",
    gurmukhiUni: "ਰਾਗੁ ਮਾਲੀ ਗਉੜਾ",
    transliteration: "raag maalee gauRaa",
    transliterations: {
      english: "raag maalee gauRaa",
      hindi: "रागु माली गउड़ा",
      en: "raag maalee gauRaa",
      hi: "रागु माली गउड़ा",
      ipa: "rɑG mɑli Goʊɽɑ",
      ur: "راگ مالیِ گاڑا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 69,
    token: "maaru",
    gurmukhi: "rwgu mwrU",
    gurmukhiUni: "ਰਾਗੁ ਮਾਰੂ",
    transliteration: "raag maaroo",
    transliterations: {
      english: "raag maaroo",
      hindi: "रागु मारू",
      en: "raag maaroo",
      hi: "रागु मारू",
      ipa: "rɑG mɑru",
      ur: "راگ مارُو",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 70,
    token: "kedaara",
    gurmukhi: "rwgu kydwrw",
    gurmukhiUni: "ਰਾਗੁ ਕੇਦਾਰਾ",
    transliteration: "raag kedhaaraa",
    transliterations: {
      english: "raag kedhaaraa",
      hindi: "रागु केदारा",
      en: "raag kedhaaraa",
      hi: "रागु केदारा",
      ipa: "rɑG ked̪ɑrɑ",
      ur: "راگ کےدارا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 71,
    token: "bhairo",
    gurmukhi: "rwgu BYrau",
    gurmukhiUni: "ਰਾਗੁ ਭੈਰਉ",
    transliteration: "raag bhairau",
    transliterations: {
      english: "raag bhairau",
      hindi: "रागु भैरउ",
      en: "raag bhairau",
      hi: "रागु भैरउ",
      ipa: "rɑG ɓæroʊ",
      ur: "راگ بھَےرا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 72,
    token: "basant",
    gurmukhi: "rwgu bsMqu",
    gurmukhiUni: "ਰਾਗੁ ਬਸੰਤੁ",
    transliteration: "raag basa(n)tu",
    transliterations: {
      english: "raag basa(n)tu",
      hindi: "रागु बसंतु",
      en: "raag basa(n)tu",
      hi: "रागु बसंतु",
      ipa: "rɑG bəsəŋt̪ʊ",
      ur: "راگ بسںت",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 73,
    token: "saarang",
    gurmukhi: "rwgu swrMg",
    gurmukhiUni: "ਰਾਗੁ ਸਾਰੰਗ",
    transliteration: "raag saara(n)g",
    transliterations: {
      english: "raag saara(n)g",
      hindi: "रागु सारंग",
      en: "raag saara(n)g",
      hi: "रागु सारंग",
      ipa: "rɑG sɑrəŋG",
      ur: "راگ سارںگ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 74,
    token: "malaar",
    gurmukhi: "rwgu mlwr",
    gurmukhiUni: "ਰਾਗੁ ਮਲਾਰ",
    transliteration: "raag malaar",
    transliterations: {
      english: "raag malaar",
      hindi: "रागु मलार",
      en: "raag malaar",
      hi: "रागु मलार",
      ipa: "rɑG məlɑr",
      ur: "راگ ملار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 75,
    token: "kaanra",
    gurmukhi: "rwgu kwnVw",
    gurmukhiUni: "ਰਾਗੁ ਕਾਨੜਾ",
    transliteration: "raag kaanaRaa",
    transliterations: {
      english: "raag kaanaRaa",
      hindi: "रागु कानड़ा",
      en: "raag kaanaRaa",
      hi: "रागु कानड़ा",
      ipa: "rɑG kɑnəɽɑ",
      ur: "راگ کانڑا",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 76,
    token: "prabhaati",
    gurmukhi: "rwgu pRBwqI",
    gurmukhiUni: "ਰਾਗੁ ਪ੍ਰਭਾਤੀ",
    transliteration: "raag prabhaatee",
    transliterations: {
      english: "raag prabhaatee",
      hindi: "रागु प्रभाती",
      en: "raag prabhaatee",
      hi: "रागु प्रभाती",
      ipa: "rɑG pɹəɓɑt̪i",
      ur: "راگ پربھاتیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 77,
    token: "salokkabir",
    gurmukhi: "slok Bgq kbIr jIau ky",
    gurmukhiUni: "ਸਲੋਕ ਭਗਤ ਕਬੀਰ ਜੀਉ ਕੇ",
    transliteration: "salok bhagat kabeer jeeau ke",
    transliterations: {
      english: "salok bhagat kabeer jeeau ke",
      hindi: "सलोक भगत कबीर जीउ के",
      en: "salok bhagat kabeer jeeau ke",
      hi: "सलोक भगत कबीर जीउ के",
      ipa: "səlɔk ɓəGət̪ kəbir d͡ʒio ke",
      ur: "سلوک بھگت کبیِر جیِا کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 78,
    token: "salokfareed",
    gurmukhi: "slok syK PrId ky",
    gurmukhiUni: "ਸਲੋਕ ਸੇਖ ਫਰੀਦ ਕੇ",
    transliteration: "salok sekh fareedh ke",
    transliterations: {
      english: "salok sekh fareedh ke",
      hindi: "सलोक सेख फरीद के",
      en: "salok sekh fareedh ke",
      hi: "सलोक सेख फरीद के",
      ipa: "səlɔk sekʰ fərid̪ ke",
      ur: "سلوک سےکھ پھریِد کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 79,
    token: "sirimukhbaakm1a",
    gurmukhi: "svXy sRI muKbwk´ mhlw 5 - 1",
    gurmukhiUni: "ਸਵਯੇ ਸ੍ਰੀ ਮੁਖਬਾਕੵ ਮਹਲਾ ੫ - ੧",
    transliteration: "savaye sree mukhabaakaye mahalaa panjavaa - 1",
    transliterations: {
      english: "savaye sree mukhabaakaye mahalaa panjavaa - 1",
      hindi: "सवये स्री मुखबाक्य महला ५ - १",
      en: "savaye sree mukhabaakaye mahalaa panjavaa - 1",
      hi: "सवये स्री मुखबाक्य महला ५ - १",
      ipa: "səʋəje sɹi mʊkʰəbɑkəj məhəlɑ pəŋd͡ʒʋɑ - 1",
      ur: "سوےے سریِ مُکھباکے مهلا ۵ - ۱",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 80,
    token: "sirimukhbaakm1b",
    gurmukhi: "svXy sRI muKbwk´ mhlw 5 - 2",
    gurmukhiUni: "ਸਵਯੇ ਸ੍ਰੀ ਮੁਖਬਾਕੵ ਮਹਲਾ ੫ - ੨",
    transliteration: "savaye sree mukhabaakaye mahalaa panjavaa - 2",
    transliterations: {
      english: "savaye sree mukhabaakaye mahalaa panjavaa - 2",
      hindi: "सवये स्री मुखबाक्य महला ५ - २",
      en: "savaye sree mukhabaakaye mahalaa panjavaa - 2",
      hi: "सवये स्री मुखबाक्य महला ५ - २",
      ipa: "səʋəje sɹi mʊkʰəbɑkəj məhəlɑ pəŋd͡ʒʋɑ - 2",
      ur: "سوےے سریِ مُکھباکے مهلا ۵ - ۲",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 81,
    token: "svaiyem1",
    gurmukhi: "sveIey mhly pihly ky",
    gurmukhiUni: "ਸਵਈਏ ਮਹਲੇ ਪਹਿਲੇ ਕੇ",
    transliteration: "savie'ee mahale pahile ke",
    transliterations: {
      english: "savie'ee mahale pahile ke",
      hindi: "सवईए महले पहिले के",
      en: "savie'ee mahale pahile ke",
      hi: "सवईए महले पहिले के",
      ipa: "səʋeiee məhəle pəhɪle ke",
      ur: "سوایاے مهلے پهِلے کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 82,
    token: "svaiyem2",
    gurmukhi: "sveIey mhly dUjy ky",
    gurmukhiUni: "ਸਵਈਏ ਮਹਲੇ ਦੂਜੇ ਕੇ",
    transliteration: "savie'ee mahale dhooje ke",
    transliterations: {
      english: "savie'ee mahale dhooje ke",
      hindi: "सवईए महले दूजे के",
      en: "savie'ee mahale dhooje ke",
      hi: "सवईए महले दूजे के",
      ipa: "səʋeiee məhəle d̪ud͡ʒe ke",
      ur: "سوایاے مهلے دُوجے کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 83,
    token: "svaiyem3",
    gurmukhi: "sveIey mhly qIjy ky",
    gurmukhiUni: "ਸਵਈਏ ਮਹਲੇ ਤੀਜੇ ਕੇ",
    transliteration: "savie'ee mahale teeje ke",
    transliterations: {
      english: "savie'ee mahale teeje ke",
      hindi: "सवईए महले तीजे के",
      en: "savie'ee mahale teeje ke",
      hi: "सवईए महले तीजे के",
      ipa: "səʋeiee məhəle t̪id͡ʒe ke",
      ur: "سوایاے مهلے تیِجے کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 84,
    token: "svaiyem4",
    gurmukhi: "sveIey mhly cauQy ky",
    gurmukhiUni: "ਸਵਈਏ ਮਹਲੇ ਚਉਥੇ ਕੇ",
    transliteration: "savie'ee mahale chauthe ke",
    transliterations: {
      english: "savie'ee mahale chauthe ke",
      hindi: "सवईए महले चउथे के",
      en: "savie'ee mahale chauthe ke",
      hi: "सवईए महले चउथे के",
      ipa: "səʋeiee məhəle t͡ʃoʊt̪ʰe ke",
      ur: "سوایاے مهلے چاتھے کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 85,
    token: "svaiyem5",
    gurmukhi: "sveIey mhly pMjvy ky",
    gurmukhiUni: "ਸਵਈਏ ਮਹਲੇ ਪੰਜਵੇ ਕੇ",
    transliteration: "savie'ee mahale pa(n)jave ke",
    transliterations: {
      english: "savie'ee mahale pa(n)jave ke",
      hindi: "सवईए महले पंजवे के",
      en: "savie'ee mahale pa(n)jave ke",
      hi: "सवईए महले पंजवे के",
      ipa: "səʋeiee məhəle pəŋd͡ʒəʋe ke",
      ur: "سوایاے مهلے پںجوے کے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 86,
    token: "siriraagkivaar",
    gurmukhi: "isrIrwg kI vwr mhlw 4",
    gurmukhiUni: "ਸਿਰੀਰਾਗ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "sireeraag kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "sireeraag kee vaar mahalaa chauthhaa",
      hindi: "सिरीराग की वार महला ४",
      en: "sireeraag kee vaar mahalaa chauthhaa",
      hi: "सिरीराग की वार महला ४",
      ipa: "sɪrirɑG ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "سِریِراگ کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 87,
    token: "maajhkivaar",
    gurmukhi: "vwr mwJ kI",
    gurmukhiUni: "ਵਾਰ ਮਾਝ ਕੀ",
    transliteration: "vaar maajh kee",
    transliterations: {
      english: "vaar maajh kee",
      hindi: "वार माझ की",
      en: "vaar maajh kee",
      hi: "वार माझ की",
      ipa: "ʋɑr mɑɖ͡ʐ ki",
      ur: "وار ماجھ کیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 88,
    token: "gaurikivaarm4",
    gurmukhi: "gauVI kI vwr mhlw 4",
    gurmukhiUni: "ਗਉੜੀ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "gauRee kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "gauRee kee vaar mahalaa chauthhaa",
      hindi: "गउड़ी की वार महला ४",
      en: "gauRee kee vaar mahalaa chauthhaa",
      hi: "गउड़ी की वार महला ४",
      ipa: "Goʊɽi ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "گاڑیِ کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 89,
    token: "gaurikivaarm5",
    gurmukhi: "gauVI kI vwr mhlw 5",
    gurmukhiUni: "ਗਉੜੀ ਕੀ ਵਾਰ ਮਹਲਾ ੫",
    transliteration: "gauRee kee vaar mahalaa panjavaa",
    transliterations: {
      english: "gauRee kee vaar mahalaa panjavaa",
      hindi: "गउड़ी की वार महला ५",
      en: "gauRee kee vaar mahalaa panjavaa",
      hi: "गउड़ी की वार महला ५",
      ipa: "Goʊɽi ki ʋɑr məhəlɑ pəŋd͡ʒʋɑ",
      ur: "گاڑیِ کیِ وار مهلا ۵",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 90,
    token: "asadivar",
    gurmukhi: "Awsw dI vwr",
    gurmukhiUni: "ਆਸਾ ਦੀ ਵਾਰ",
    transliteration: "aasaa dhee vaar",
    transliterations: {
      english: "aasaa dhee vaar",
      hindi: "आसा दी वार",
      en: "aasaa dhee vaar",
      hi: "आसा दी वार",
      ipa: "əɑsɑ d̪i ʋɑr",
      ur: "آسا دیِ وار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 91,
    token: "gujrikivaarm3",
    gurmukhi: "gUjrI kI vwr mhlw 3",
    gurmukhiUni: "ਗੂਜਰੀ ਕੀ ਵਾਰ ਮਹਲਾ ੩",
    transliteration: "goojaree kee vaar mahalaa teejaa",
    transliterations: {
      english: "goojaree kee vaar mahalaa teejaa",
      hindi: "गूजरी की वार महला ३",
      en: "goojaree kee vaar mahalaa teejaa",
      hi: "गूजरी की वार महला ३",
      ipa: "Gud͡ʒəri ki ʋɑr məhəlɑ t̪id͡ʒɑ",
      ur: "گُوجریِ کیِ وار مهلا ۳",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 92,
    token: "gujrikivaarm5",
    gurmukhi: "rwgu gUjrI vwr mhlw 5",
    gurmukhiUni: "ਰਾਗੁ ਗੂਜਰੀ ਵਾਰ ਮਹਲਾ ੫",
    transliteration: "raag goojaree vaar mahalaa panjavaa",
    transliterations: {
      english: "raag goojaree vaar mahalaa panjavaa",
      hindi: "रागु गूजरी वार महला ५",
      en: "raag goojaree vaar mahalaa panjavaa",
      hi: "रागु गूजरी वार महला ५",
      ipa: "rɑG Gud͡ʒəri ʋɑr məhəlɑ pəŋd͡ʒʋɑ",
      ur: "راگ گُوجریِ وار مهلا ۵",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 93,
    token: "bihagrakivaarm4",
    gurmukhi: "ibhwgVy kI vwr mhlw 4",
    gurmukhiUni: "ਬਿਹਾਗੜੇ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "bihaagaRe kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "bihaagaRe kee vaar mahalaa chauthhaa",
      hindi: "बिहागड़े की वार महला ४",
      en: "bihaagaRe kee vaar mahalaa chauthhaa",
      hi: "बिहागड़े की वार महला ४",
      ipa: "bɪhɑGəɽe ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "بِهاگڑے کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 94,
    token: "vadhanskeevaarm4",
    gurmukhi: "vfhMs kI vwr mhlw 4",
    gurmukhiUni: "ਵਡਹੰਸ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "vaddaha(n)s kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "vaddaha(n)s kee vaar mahalaa chauthhaa",
      hindi: "वडहंस की वार महला ४",
      en: "vaddaha(n)s kee vaar mahalaa chauthhaa",
      hi: "वडहंस की वार महला ४",
      ipa: "ʋəɖəhəŋs ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "وڈهںس کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 95,
    token: "soratkivaarm4",
    gurmukhi: "rwgu soriT vwr mhly 4 kI",
    gurmukhiUni: "ਰਾਗੁ ਸੋਰਠਿ ਵਾਰ ਮਹਲੇ ੪ ਕੀ",
    transliteration: "raag soraTh vaar mahale 4 kee",
    transliterations: {
      english: "raag soraTh vaar mahale 4 kee",
      hindi: "रागु सोरठि वार महले ४ की",
      en: "raag soraTh vaar mahale 4 kee",
      hi: "रागु सोरठि वार महले ४ की",
      ipa: "rɑG sɔrəʈʰ ʋɑr məhəle 4 ki",
      ur: "راگ سورٹھ وار مهلے ۴ کیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 96,
    token: "jaitsrikivar",
    gurmukhi: "jYqsrI kI vwr",
    gurmukhiUni: "ਜੈਤਸਰੀ ਕੀ ਵਾਰ",
    transliteration: "jaitasaree kee vaar",
    transliterations: {
      english: "jaitasaree kee vaar",
      hindi: "जैतसरी की वार",
      en: "jaitasaree kee vaar",
      hi: "जैतसरी की वार",
      ipa: "d͡ʒæt̪əsəri ki ʋɑr",
      ur: "جَےتسریِ کیِ وار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 97,
    token: "soohikivaar",
    gurmukhi: "vwr sUhI kI",
    gurmukhiUni: "ਵਾਰ ਸੂਹੀ ਕੀ",
    transliteration: "vaar soohee kee",
    transliterations: {
      english: "vaar soohee kee",
      hindi: "वार सूही की",
      en: "vaar soohee kee",
      hi: "वार सूही की",
      ipa: "ʋɑr suhi ki",
      ur: "وار سُوهیِ کیِ",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 98,
    token: "bilaavalkivaar",
    gurmukhi: "iblwvlu kI vwr mhlw 4",
    gurmukhiUni: "ਬਿਲਾਵਲੁ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "bilaaval kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "bilaaval kee vaar mahalaa chauthhaa",
      hindi: "बिलावलु की वार महला ४",
      en: "bilaaval kee vaar mahalaa chauthhaa",
      hi: "बिलावलु की वार महला ४",
      ipa: "bɪlɑʋəl ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "بِلاول کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 99,
    token: "ramkalikivaarm3",
    gurmukhi: "rwmklI kI vwr mhlw 3",
    gurmukhiUni: "ਰਾਮਕਲੀ ਕੀ ਵਾਰ ਮਹਲਾ ੩",
    transliteration: "raamakalee kee vaar mahalaa teejaa",
    transliterations: {
      english: "raamakalee kee vaar mahalaa teejaa",
      hindi: "रामकली की वार महला ३",
      en: "raamakalee kee vaar mahalaa teejaa",
      hi: "रामकली की वार महला ३",
      ipa: "rɑməkəli ki ʋɑr məhəlɑ t̪id͡ʒɑ",
      ur: "رامکلیِ کیِ وار مهلا ۳",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 100,
    token: "ramkalikivaarm5",
    gurmukhi: "rwmklI kI vwr mhlw 5",
    gurmukhiUni: "ਰਾਮਕਲੀ ਕੀ ਵਾਰ ਮਹਲਾ ੫",
    transliteration: "raamakalee kee vaar mahalaa panjavaa",
    transliterations: {
      english: "raamakalee kee vaar mahalaa panjavaa",
      hindi: "रामकली की वार महला ५",
      en: "raamakalee kee vaar mahalaa panjavaa",
      hi: "रामकली की वार महला ५",
      ipa: "rɑməkəli ki ʋɑr məhəlɑ pəŋd͡ʒʋɑ",
      ur: "رامکلیِ کیِ وار مهلا ۵",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 101,
    token: "ramkalikivar",
    gurmukhi: "rwmklI kI vwr (rwie blvMif qQw sqY)",
    gurmukhiUni: "ਰਾਮਕਲੀ ਕੀ ਵਾਰ (ਰਾਇ ਬਲਵੰਡਿ ਤਥਾ ਸਤੈ)",
    transliteration: "raamakalee kee vaar (rai balava(n)dd tathaa satai)",
    transliterations: {
      english: "raamakalee kee vaar (rai balava(n)dd tathaa satai)",
      hindi: "रामकली की वार (राइ बलवंडि तथा सतै)",
      en: "raamakalee kee vaar (rai balava(n)dd tathaa satai)",
      hi: "रामकली की वार (राइ बलवंडि तथा सतै)",
      ipa: "rɑməkəli ki ʋɑr (rɑeɪ bələʋəŋɖ t̪ət̪ʰɑ sət̪æ)",
      ur: "رامکلیِ کیِ وار (راا بلوںڈ تتھا ستَے)",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 102,
    token: "maarookivaarm3",
    gurmukhi: "mwrU vwr mhlw 3",
    gurmukhiUni: "ਮਾਰੂ ਵਾਰ ਮਹਲਾ ੩",
    transliteration: "maaroo vaar mahalaa teejaa",
    transliterations: {
      english: "maaroo vaar mahalaa teejaa",
      hindi: "मारू वार महला ३",
      en: "maaroo vaar mahalaa teejaa",
      hi: "मारू वार महला ३",
      ipa: "mɑru ʋɑr məhəlɑ t̪id͡ʒɑ",
      ur: "مارُو وار مهلا ۳",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 103,
    token: "vaarmaroodakhnem5",
    gurmukhi: "mwrU vwr mhlw 5 fKxy",
    gurmukhiUni: "ਮਾਰੂ ਵਾਰ ਮਹਲਾ ੫ ਡਖਣੇ",
    transliteration: "maaroo vaar mahalaa panjavaa ddakhane",
    transliterations: {
      english: "maaroo vaar mahalaa panjavaa ddakhane",
      hindi: "मारू वार महला ५ डखणे",
      en: "maaroo vaar mahalaa panjavaa ddakhane",
      hi: "मारू वार महला ५ डखणे",
      ipa: "mɑru ʋɑr məhəlɑ pəŋd͡ʒʋɑ ɖəkʰəɳe",
      ur: "مارُو وار مهلا ۵ ڈکھݨے",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 104,
    token: "basantkivar",
    gurmukhi: "bsMq kI vwr",
    gurmukhiUni: "ਬਸੰਤ ਕੀ ਵਾਰ",
    transliteration: "basa(n)t kee vaar",
    transliterations: {
      english: "basa(n)t kee vaar",
      hindi: "बसंत की वार",
      en: "basa(n)t kee vaar",
      hi: "बसंत की वार",
      ipa: "bəsəŋt̪ ki ʋɑr",
      ur: "بسںت کیِ وار",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 105,
    token: "sarangkivaarm4",
    gurmukhi: "swrMg kI vwr mhlw 4",
    gurmukhiUni: "ਸਾਰੰਗ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "saara(n)g kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "saara(n)g kee vaar mahalaa chauthhaa",
      hindi: "सारंग की वार महला ४",
      en: "saara(n)g kee vaar mahalaa chauthhaa",
      hi: "सारंग की वार महला ४",
      ipa: "sɑrəŋG ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "سارںگ کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 106,
    token: "malaarkivaarm1",
    gurmukhi: "vwr mlwr kI mhlw 1",
    gurmukhiUni: "ਵਾਰ ਮਲਾਰ ਕੀ ਮਹਲਾ ੧",
    transliteration: "vaar malaar kee mahalaa pehilaa",
    transliterations: {
      english: "vaar malaar kee mahalaa pehilaa",
      hindi: "वार मलार की महला १",
      en: "vaar malaar kee mahalaa pehilaa",
      hi: "वार मलार की महला १",
      ipa: "ʋɑr məlɑr ki məhəlɑ pəhɪlɑ",
      ur: "وار ملار کیِ مهلا ۱",
    },
    updated: "2022-12-24 00:22:33",
  },
  {
    ID: 107,
    token: "kaanrekivaarm4",
    gurmukhi: "kwnVy kI vwr mhlw 4",
    gurmukhiUni: "ਕਾਨੜੇ ਕੀ ਵਾਰ ਮਹਲਾ ੪",
    transliteration: "kaanaRe kee vaar mahalaa chauthhaa",
    transliterations: {
      english: "kaanaRe kee vaar mahalaa chauthhaa",
      hindi: "कानड़े की वार महला ४",
      en: "kaanaRe kee vaar mahalaa chauthhaa",
      hi: "कानड़े की वार महला ४",
      ipa: "kɑnəɽe ki ʋɑr məhəlɑ t͡ʃɵɵt̪ʰɑ",
      ur: "کانڑے کیِ وار مهلا ۴",
    },
    updated: "2022-12-24 00:22:33",
  },
];

const Bani_Display_Order = [
  {
    title: "Nitnem",
    banis: [
      { token: "japji" },
      { token: "jaap" },
      { token: "svaiye" },
      { token: "chaupai" },
      { token: "anand" },
    ],
  },
  {
    title: "Fun Size",
    banis: [
      { token: "lavaa" },
      { token: "kuchji" },
      { token: "suchji" },
      { token: "gunvanti" },
      { token: "funhem5" },
      { token: "chaubole" },
      { token: "ramkalikivar" },
      { token: "basantkivar" },
    ],
  },
  {
    title: "5 Granthi",
    banis: [
      { token: "sukhmani" },
      { token: "asadivar" },
      { token: "bavanakhree" },
      { token: "sidhgosht" },
      { token: "dhakhnioankar" },
    ],
  },
  {
    title: "22 Vaaran",
    banis: [
      { token: "siriraagkivaar" },
      { token: "maajhkivaar" },
      { token: "gaurikivaarm4" },
      { token: "gaurikivaarm5" },
      { token: "asadivar" },
      { token: "gujrikivaarm3" },
      { token: "gujrikivaarm5" },
      { token: "bihagrakivaarm4" },
      { token: "vadhanskeevaarm4" },
      { token: "soratkivaarm4" },
      { token: "jaitsrikivar" },
      { token: "soohikivaar" },
      { token: "bilaavalkivaar" },
      { token: "ramkalikivaarm3" },
      { token: "ramkalikivaarm5" },
      { token: "ramkalikivar" },
      { token: "maarookivaarm3" },
      { token: "vaarmaroodakhnem5" },
      { token: "basantkivar" },
      { token: "sarangkivaarm4" },
      { token: "malaarkivaarm1" },
      { token: "kaanrekivaarm4" },
    ],
  },
  // { title: "Bhagat Bani", banis: [ { token: "sriraag" }, { token: "gauri" }, { token: "aasa" }, { token: "gujri" }, { token: "sorat" }, { token: "dhanasari" }, { token: "jaitsree" }, { token: "toddee" }, { token: "tilang" }, { token: "soohee" }, { token: "bilaaval" }, { token: "gond" }, { token: "ramkali" }, { token: "maaligauri" }, { token: "maaru" }, { token: "kedaara" }, { token: "bhairo" }, { token: "basant" }, { token: "saarang" }, { token: "malaar" }, { token: "kaanra" }, { token: "prabhaati" }, { token: "salokkabir" }, { token: "salokfareed" }, ], },
  {
    title: "Svaiye",
    banis: [
      { token: "sirimukhbaakm1a" },
      { token: "sirimukhbaakm1b" },
      { token: "svaiyem1" },
      { token: "svaiyem2" },
      { token: "svaiyem3" },
      { token: "svaiyem4" },
      { token: "svaiyem5" },
    ],
  },
  {
    title: "Dasam",
    banis: [
      { token: "ogardanti" },
      { token: "akalustat" },
      { token: "chandidivar" },
      { token: "shastarnaammala" },
    ],
  },
  {
    title: "ALL",
    banis: [
      { token: "japji" },
      { token: "shabadhazare" },
      { token: "jaap" },
      { token: "shabadhazare10" },
      { token: "svaiye" },
      { token: "svaiyedeenan" },
      { token: "akaalustatchaupai" },
      { token: "chaupai" },
      { token: "anand" },
      { token: "lavaa" },
      { token: "athchandichariter" },
      { token: "chandidivar" },
      { token: "kuchji" },
      { token: "suchji" },
      { token: "gunvanti" },
      { token: "funhem5" },
      { token: "chaubole" },
      { token: "shastarnaammala" },
      { token: "rehras" },
      { token: "aarti" },
      { token: "sohila" },
      { token: "ardas" },
      { token: "bhagautiastotr" },
      { token: "bhagautiastotrhazoor" },
      { token: "baarehmaha" },
      { token: "baarehmahasvaye" },
      { token: "akalustat" },
      { token: "salokm9" },
      { token: "sukhmani" },
      { token: "sukhmana" },
      { token: "bavanakhree" },
      { token: "sidhgosht" },
      { token: "dhakhnioankar" },
      { token: "dukhbhanjani" },
      { token: "raagmala" },
      { token: "baavanakhrikabirjee" },
      { token: "ghorrian" },
      { token: "karhalai" },
      { token: "birharre" },
      { token: "patteelikhee" },
      { token: "patteem3" },
      { token: "ruteem5" },
      { token: "sadd" },
      { token: "thitteekabirjee" },
      { token: "thitteem1" },
      { token: "thitteem5" },
      { token: "vaarkabirjee" },
      { token: "vaarsat" },
      { token: "vanjaara" },
      { token: "ogardanti" },
      { token: "sriraag" },
      { token: "gauri" },
      { token: "aasa" },
      { token: "gujri" },
      { token: "sorat" },
      { token: "dhanasari" },
      { token: "jaitsree" },
      { token: "toddee" },
      { token: "tilang" },
      { token: "soohee" },
      { token: "bilaaval" },
      { token: "gond" },
      { token: "ramkali" },
      { token: "maaligauri" },
      { token: "maaru" },
      { token: "kedaara" },
      { token: "bhairo" },
      { token: "basant" },
      { token: "saarang" },
      { token: "malaar" },
      { token: "kaanra" },
      { token: "prabhaati" },
      { token: "salokkabir" },
      { token: "salokfareed" },
      { token: "sirimukhbaakm1a" },
      { token: "sirimukhbaakm1b" },
      { token: "svaiyem1" },
      { token: "svaiyem2" },
      { token: "svaiyem3" },
      { token: "svaiyem4" },
      { token: "svaiyem5" },
      { token: "siriraagkivaar" },
      { token: "maajhkivaar" },
      { token: "gaurikivaarm4" },
      { token: "gaurikivaarm5" },
      { token: "asadivar" },
      { token: "gujrikivaarm3" },
      { token: "gujrikivaarm5" },
      { token: "bihagrakivaarm4" },
      { token: "vadhanskeevaarm4" },
      { token: "soratkivaarm4" },
      { token: "jaitsrikivar" },
      { token: "soohikivaar" },
      { token: "bilaavalkivaar" },
      { token: "ramkalikivaarm3" },
      { token: "ramkalikivaarm5" },
      { token: "ramkalikivar" },
      { token: "maarookivaarm3" },
      { token: "vaarmaroodakhnem5" },
      { token: "basantkivar" },
      { token: "sarangkivaarm4" },
      { token: "malaarkivaarm1" },
      { token: "kaanrekivaarm4" },
    ],
  },
];

const bani_partitions = {
  japji: [
    0, 10, 30, 48, 60, 84, 108, 132, 171, 199, 208, 267, 289, 299, 316, 335,
    371, 378,
  ],
  jaap: [0, 181, 248, 309, 342, 410, 531, 602, 688, 745, 762],
  svaiye: [0, 7, 11, 15, 19, 23, 27, 31, 35, 39],
  chaupai: [
    0, 5, 42, 54, 62, 70, 78, 86, 94, 102, 110, 118, 126, 134, 142, 154, 159,
    165, 170,
  ],
  anand: [
    0, 7, 12, 17, 23, 28, 33, 38, 43, 48, 54, 60, 65, 70, 76, 81, 86, 91, 96,
    101, 106, 111, 116, 121, 127, 132, 137, 142, 147, 153, 158, 163, 168, 173,
    179, 184, 189, 194, 199, 204,
  ],
  sukhmani: [
    0, 90, 174, 258, 341, 424, 508, 593, 678, 764, 848, 932, 1016, 1100, 1184,
    1266, 1349, 1433, 1515, 1599, 1683, 1767, 1851, 1935,
  ],
  asadivar: [
    0, 27, 67, 105, 141, 185, 216, 254, 282, 324, 358, 392, 421, 453, 484, 524,
    563, 585, 613, 643, 669, 689, 721, 738,
  ],
  bavanakhree: [
    0, 26, 38, 50, 61, 73, 84, 96, 108, 120, 132, 144, 156, 168, 178, 190, 202,
    214, 226, 238, 250, 262, 273, 285, 297, 309, 321, 333, 344, 356, 368, 380,
    392, 404, 415, 427, 437, 449, 461, 473, 485, 497, 508, 522, 533, 545, 556,
    567, 578, 590, 602, 613, 625, 637, 649,
  ],
  sidhgosht: [
    0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 82, 94, 106, 118, 130, 142, 154, 172,
    190, 202, 220, 232, 250, 268, 279, 291, 303, 321, 333, 345, 357, 369, 381,
    393,
  ],
  dhakhnioankar: [
    0, 12, 16, 20, 24, 28, 32, 40, 48, 56, 64, 68, 72, 80, 88, 96, 104, 112,
    120, 128, 136, 145, 153, 161, 169, 177, 185, 194, 202, 210, 218, 226, 234,
    242, 250, 254, 262, 270, 278, 287, 295, 303, 311, 319, 327, 335, 343, 351,
    359, 367, 375, 383, 391, 395,
  ],
  ogardanti: [0, 52, 100, 148, 196, 244, 294],
  akalustat: [
    0, 49, 90, 131, 212, 293, 374, 495, 576, 657, 738, 819, 840, 921, 970, 1011,
    1068,
  ],

  // fun size
  lavaa: [0, 8, 14, 20],
  kuchji: [0],
  suchji: [0],
  gunvanti: [0],
  funhem5: [
    0, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
    78, 82, 86, 90,
  ],
  chaubole: [0],

  // 22 vaaraan
  siriraagkivaar: [
    0, 19, 31, 63, 78, 91, 108, 127, 151, 167, 189, 217, 234, 265, 277, 297,
    313, 332, 347, 361,
  ],
  maajhkivaar: [
    0, 37, 61, 80, 124, 144, 170, 188, 291, 330, 354, 377, 397, 423, 452, 474,
    494, 511, 534, 552, 569, 584, 623, 643,
  ],
  gaurikivaarm4: [
    0, 19, 33, 45, 57, 73, 92, 115, 140, 164, 187, 209, 235, 258, 287, 322, 342,
    362, 382, 401, 431, 453, 472, 488, 504, 520, 542, 554, 566, 578, 608, 632,
    647,
  ],
  gaurikivaarm5: [
    0, 19, 31, 43, 55, 67, 79, 91, 103, 117, 129, 141, 153, 165, 177, 189, 210,
    222, 234, 246, 260,
  ],
  // asadivar: [0],
  gujrikivaarm3: [
    0, 18, 35, 48, 64, 84, 98, 116, 134, 149, 169, 187, 208, 225, 242, 260, 277,
    297, 318, 343, 352, 366,
  ],
  gujrikivaarm5: [
    0, 25, 42, 57, 72, 87, 117, 132, 147, 162, 177, 192, 207, 222, 230, 251,
    266, 281, 296, 318,
  ],
  bihagrakivaarm4: [
    0, 16, 37, 52, 74, 86, 102, 118, 134, 152, 169, 183, 204, 218, 230, 248,
    267, 282, 302, 319, 333,
  ],
  vadhanskeevaarm4: [
    0, 19, 35, 57, 81, 103, 122, 138, 155, 174, 188, 205, 218, 232, 248, 268,
    285, 301, 321, 337, 349,
  ],
  soratkivaarm4: [
    0, 23, 40, 61, 82, 96, 119, 134, 151, 168, 185, 201, 221, 241, 255, 280,
    296, 314, 330, 345, 363, 378, 396, 411, 429, 446, 466, 478,
  ],
  jaitsrikivar: [
    0, 13, 24, 35, 46, 57, 68, 79, 90, 101, 112, 123, 135, 146, 157, 168, 179,
    190, 201, 212,
  ],
  soohikivaar: [
    0, 20, 36, 54, 72, 90, 107, 125, 138, 157, 173, 185, 199, 219, 235, 256,
    270, 289, 301, 316,
  ],
  bilaavalkivaar: [0, 20, 39, 57, 76, 95, 110, 134, 155, 170, 188, 200, 221],
  ramkalikivaarm3: [
    0, 30, 43, 61, 80, 98, 114, 134, 165, 186, 204, 252, 314, 336, 366, 380,
    399, 415, 434, 461, 473,
  ],
  ramkalikivaarm5: [
    0, 21, 40, 58, 82, 114, 143, 183, 212, 227, 248, 273, 298, 313, 328, 343,
    358, 375, 393, 408, 423, 438,
  ],
  ramkalikivar: [0, 9, 22, 34, 43, 52, 71, 80],
  maarookivaarm3: [
    0, 18, 38, 53, 67, 79, 91, 104, 116, 136, 152, 166, 180, 195, 212, 229, 246,
    271, 284, 303, 315, 327,
  ],
  vaarmaroodakhnem5: [
    0, 19, 37, 55, 73, 91, 109, 127, 145, 163, 199, 217, 235, 253, 271, 289,
    307, 325, 343, 361, 380, 399,
  ],
  basantkivar: [0, 7, 12],
  sarangkivaarm4: [
    0, 30, 50, 70, 88, 108, 131, 153, 171, 195, 212, 234, 251, 267, 283, 309,
    330, 345, 359, 373, 391, 408, 430, 449, 467, 484, 496, 513, 528, 541, 556,
    572, 597, 614, 637, 653,
  ],
  malaarkivaarm1: [
    0, 18, 41, 58, 73, 90, 107, 129, 152, 170, 190, 210, 229, 248, 263, 282,
    300, 315, 336, 371, 397, 427, 452, 471, 501, 546, 561, 590,
  ],
  kaanrekivaarm4: [
    0, 18, 34, 52, 73, 92, 109, 121, 135, 152, 167, 182, 194, 206, 221,
  ],

  // savyie
  sirimukhbaakm1a: [0, 10, 15, 20, 25, 31, 37, 43, 49],
  sirimukhbaakm1b: [0, 9, 15, 21, 27, 35, 43, 49, 55, 61, 66],
  svaiyem1: [0, 6, 10, 14, 18, 22, 28, 34, 40, 46],
  svaiyem2: [0, 8, 12, 16, 20, 26, 32, 38, 42, 46],
  svaiyem3: [
    0, 10, 14, 18, 22, 28, 32, 36, 40, 46, 53, 59, 65, 71, 77, 83, 89, 95, 101,
    108, 114, 120,
  ],
  svaiyem4: [
    0, 14, 18, 22, 26, 32, 38, 44, 50, 56, 60, 66, 70, 74, 79, 84, 89, 94, 99,
    105, 111, 117, 122, 127, 132, 137, 143, 148, 153, 158, 178, 184, 190, 196,
    200, 205, 209, 213, 218, 223, 228, 233, 238, 244, 248, 252, 256, 260, 264,
    268, 276, 280, 284, 288, 294, 298, 302, 306, 310, 316,
  ],
  svaiyem5: [
    0, 14, 18, 22, 26, 32, 36, 42, 48, 52, 53, 59, 65, 71, 75, 79, 83, 87, 93,
    99,
  ],
};

export { ALL_BANIS_DATA, bani_partitions, Bani_Display_Order };
